# Generated by Django 5.2.5 on 2025-09-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
