# Generated by Django 5.2.5 on 2026-01-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_taskrequest_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('EL', 'Electrician'), ('PB', 'Plumbing repairs'), ('MV', 'Moving'), ('GD', 'Gardening'), ('CL', 'Cleaning'), ('CP', 'Carpentry'), ('HR', 'Home Repairs'), ('VA', 'Virtual Assistant')], max_length=2),
        ),
    ]
